name: Build and Publish to Github Package Registry

on:
  push:
    branches: [production]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy package.json to root directory
        run: cp backEndExpress/package.json .

      - name: Read Version Number from package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Lowercase Repo Name for Docker Image Tag
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.4

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # Location of the DockerFile
          context: .
          platforms: linux/arm64, #linux/amd64, linux/arm
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.package-version.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_publish
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy package.json to root directory
        run: cp backEndExpress/package.json .

      - name: Read Version Number from package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Lowercase Repo Name for Docker Image Tag
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Deploy to caprover
        run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl ${{ secrets.C_URL }} --caproverPassword ${{ secrets.C_PASS }} --caproverApp ${{ secrets.C_APP }} --imageName ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.package-version.outputs.version }}
